### PR TITLE
Prototype

### PR DESCRIPTION
**Pull request by ghosh**
Added dot grid and draggable controls.

- [x] Canvas Component
- [x] Control Component
- [x] Daraggable

### CODE REVIEW

**Review by eeshdarthvader — APPROVED** [review]
LGTM

**Comment by eeshdarthvader** [comment]
Few points.

1.  Move `Control` and `Label` component in `components/common` folder
2. Files are not prettified. Apply the prettier.json to your editor (i will add husky and eslint in a separate PR)

**Comment by ghosh** [comment]
@blnarayanan92 Have a look at the styles. Fell free to change anything.

@eeshdarthvader It's just a static site now. Do you want to pick up the reactivity?

**Comment by eeshdarthvader** [comment]
> @blnarayanan92 Have a look at the styles. Fell free to change anything.
> 
> @eeshdarthvader It's just a static site now. Do you want to pick up the reactivity? 

Yes, I will pick up reactivity.

If this pr is ready then merge this PR for cleanup.

I will raise PR for reactivity and more plumbing

**Pull request merged**
