### PR TITLE
Reactivity part 2 with Grid types

### PR DESCRIPTION
**Pull request by eeshdarthvader**
Preview: https://gridster-git-reactivitypart2.eeshdarthvader.vercel.app/

- [x] Make `Range` component more flexible to accept `min`, `max` and `displayUnit`
- [x] Add Grid types design
- [x] Render Grids svgs based on selected values
- [x] Reactivity for grids

### CODE REVIEW

**Comment by eeshdarthvader** [comment]
@ghosh  Please check the designs of Grid boxes. May be you can refine it. Feel free to change it.

**Review by ghosh — APPROVED** [review]
👍 Looks good for now. Would probably have to revisit the colours and grid controls designs.

**Comment by ghosh** [comment]
@eeshdarthvader Seems like opacity for the line grid is not working properly. Also might as well add the square grid.

**Comment by eeshdarthvader** [comment]
> @eeshdarthvader Seems like opacity for the line grid is not working properly. Also might as well add the square grid.

Added square grid.

**Pull request merged**
